spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8762

#keycloak:
#  realm: cydeo-dev
#  auth-server-url: http://${KEYCLOAK}:8080/auth
#  ssl-required: none
#  resource: ticketing-app
#  credentials:
#    secret: H60klvIQaHbGzOE8yDTDknMp2D1oYBof
#  use-resource-role-mappings: true
#  bearer-only: true

eureka:
  instance:
#    preferIpAddress: true
#    ipAddress: localhost
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://3.72.87.233:8761/eureka/

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator

info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application Gateway Service
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
