spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK}:8080/auth/realms/cydeo-dev

server:
  port: 8762

eureka:
  instance:
    preferIpAddress: true
    ipAddress: ${HOST}
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}:8761/eureka/

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://${HOST}:${server.port}/actuator

info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application Gateway Service
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

springdoc:
  swagger-ui:
    urls[0]:
      name: User Service API Doc
      url: /user-service/v3/api-docs
    urls[1]:
      name: Project Service API Doc
      url: /project-service/v3/api-docs
    urls[2]:
      name: Task Service API Doc
      url: /task-service/v3/api-docs
    urls[3]:
      name: Gateway Service API Doc
      url: /v3/api-docs
